version: '3.8'

services:
  nextjs-app:
    image: ghcr.io/maodehka/devops:test
    container_name: nextjs-test
    ports:
      - "3001:3000"  
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=test
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge