name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            source ~/.profile
            source ~/.bashrc
            cd ~/devops
            git pull origin main
            npm install
            npm run build
            pm2 restart 0 || pm2 start npm --name "devops" -- start