name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd devops
            git pull
            /home/ubuntu/.nvm/versions/node/v24.2.0/bin/npm install
            /home/ubuntu/.nvm/versions/node/v24.2.0/bin/npm run build
            /ubuntu/.nvm/versions/node/v24.2.0/bin/pm2 restart npm